.PHONY: build run

install_all:
	brew install fd
	brew install bat
	brew install ripgrep
	brew install eza
	brew install nvim
	brew install tldr
	brew install htop
	brew install peco
	brew install fzf
install_fd:
	brew install fd
install_bat:
	brew install bat
install_ripgrep:
	brew install ripgrep
install_eza:
	brew install eza
install_nvim:
	brew install nvim
install_tldr:
	brew install tldr
install_htop:
	brew install htop
install_peco:
	brew install peco
install_fzf:
	brew install fzf
setup:
	../common/bin/setup.sh ${INI_FILE}
